"use client";

export const data = [
  {
    product_id: "P1001",
    date: "2024-10-01",
    customer: "John Doe",
    status: "Shipped",
    email: "john.doe@example.com",
    country: "USA",
    total_price: "$120.00",
    quantity: 2,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1002",
    date: "2024-10-02",
    customer: "Jane Smith",
    status: "Pending",
    email: "jane.smith@example.com",
    country: "Canada",
    total_price: "$250.00",
    quantity: 5,
    payment_method: "PayPal",
  },
  {
    product_id: "P1003",
    date: "2024-10-03",
    customer: "Robert Brown",
    status: "Delivered",
    email: "robert.brown@example.com",
    country: "UK",
    total_price: "$85.00",
    quantity: 1,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1004",
    date: "2024-10-04",
    customer: "Emily Johnson",
    status: "Canceled",
    email: "emily.johnson@example.com",
    country: "Australia",
    total_price: "$60.00",
    quantity: 3,
    payment_method: "Bank Transfer",
  },
  {
    product_id: "P1005",
    date: "2024-10-05",
    customer: "Michael Davis",
    status: "Shipped",
    email: "michael.davis@example.com",
    country: "Germany",
    total_price: "$150.00",
    quantity: 4,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1006",
    date: "2024-10-06",
    customer: "Sophia Martinez",
    status: "Pending",
    email: "sophia.martinez@example.com",
    country: "USA",
    total_price: "$70.00",
    quantity: 2,
    payment_method: "PayPal",
  },
  {
    product_id: "P1007",
    date: "2024-10-07",
    customer: "Liam Wilson",
    status: "Delivered",
    email: "liam.wilson@example.com",
    country: "Germany",
    total_price: "$130.00",
    quantity: 1,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1008",
    date: "2024-10-08",
    customer: "Olivia Garcia",
    status: "Canceled",
    email: "olivia.garcia@example.com",
    country: "Australia",
    total_price: "$45.00",
    quantity: 2,
    payment_method: "Bank Transfer",
  },
  {
    product_id: "P1009",
    date: "2024-10-09",
    customer: "James Thomas",
    status: "Shipped",
    email: "james.thomas@example.com",
    country: "USA",
    total_price: "$200.00",
    quantity: 3,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1010",
    date: "2024-10-10",
    customer: "Charlotte Lee",
    status: "Pending",
    email: "charlotte.lee@example.com",
    country: "UK",
    total_price: "$95.00",
    quantity: 1,
    payment_method: "PayPal",
  },
  {
    product_id: "P1011",
    date: "2024-10-11",
    customer: "Noah Harris",
    status: "Delivered",
    email: "noah.harris@example.com",
    country: "USA",
    total_price: "$65.00",
    quantity: 4,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1012",
    date: "2024-10-12",
    customer: "Emma Clark",
    status: "Shipped",
    email: "emma.clark@example.com",
    country: "Germany",
    total_price: "$110.00",
    quantity: 2,
    payment_method: "PayPal",
  },
  {
    product_id: "P1013",
    date: "2024-10-13",
    customer: "Benjamin Walker",
    status: "Canceled",
    email: "benjamin.walker@example.com",
    country: "Australia",
    total_price: "$50.00",
    quantity: 3,
    payment_method: "Bank Transfer",
  },
  {
    product_id: "P1014",
    date: "2024-10-14",
    customer: "Ava King",
    status: "Pending",
    email: "ava.king@example.com",
    country: "UK",
    total_price: "$180.00",
    quantity: 1,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1015",
    date: "2024-10-15",
    customer: "Ethan Adams",
    status: "Shipped",
    email: "ethan.adams@example.com",
    country: "Canada",
    total_price: "$75.00",
    quantity: 5,
    payment_method: "PayPal",
  },
  {
    product_id: "P1016",
    date: "2024-10-16",
    customer: "Isabella Hall",
    status: "Delivered",
    email: "isabella.hall@example.com",
    country: "Canada",
    total_price: "$135.00",
    quantity: 2,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1017",
    date: "2024-10-17",
    customer: "Mason Allen",
    status: "Canceled",
    email: "mason.allen@example.com",
    country: "UK",
    total_price: "$55.00",
    quantity: 3,
    payment_method: "Bank Transfer",
  },
  {
    product_id: "P1018",
    date: "2024-10-18",
    customer: "Mia Scott",
    status: "Shipped",
    email: "mia.scott@example.com",
    country: "USA",
    total_price: "$165.00",
    quantity: 1,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1019",
    date: "2024-10-19",
    customer: "Elijah Young",
    status: "Pending",
    email: "elijah.young@example.com",
    country: "Germany",
    total_price: "$90.00",
    quantity: 4,
    payment_method: "PayPal",
  },
  {
    product_id: "P1020",
    date: "2024-10-20",
    customer: "Amelia Perez",
    status: "Delivered",
    email: "amelia.perez@example.com",
    country: "UK",
    total_price: "$105.00",
    quantity: 2,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1021",
    date: "2024-10-21",
    customer: "Logan Robinson",
    status: "Shipped",
    email: "logan.robinson@example.com",
    country: "USA",
    total_price: "$140.00",
    quantity: 3,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1022",
    date: "2024-10-22",
    customer: "Harper White",
    status: "Pending",
    email: "harper.white@example.com",
    country: "Canada",
    total_price: "$125.00",
    quantity: 1,
    payment_method: "PayPal",
  },
  {
    product_id: "P1023",
    date: "2024-10-23",
    customer: "Lucas Wright",
    status: "Delivered",
    email: "lucas.wright@example.com",
    country: "Australia",
    total_price: "$85.00",
    quantity: 2,
    payment_method: "Credit Card",
  },
  {
    product_id: "P1024",
    date: "2024-10-24",
    customer: "Ella Martinez",
    status: "Shipped",
    email: "ella.martinez@example.com",
    country: "Germany",
    total_price: "$115.00",
    quantity: 5,
    payment_method: "PayPal",
  },
  {
    product_id: "P1025",
    date: "2024-10-25",
    customer: "Henry Lewis",
    status: "Pending",
    email: "henry.lewis@example.com",
    country: "Canada",
    total_price: "$60.00",
    quantity: 2,
    payment_method: "Credit Card",
  },
];
